#Imports

In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
import pickle

In [28]:
import numpy as np

In [9]:
import lightgbm as lgb

In [45]:
from sklearn.preprocessing import StandardScaler

In [71]:
from sklearn.metrics import mean_squared_error

In [73]:
import plotly.express as px

#Data frame creation

In [55]:
!gdown --id 1-ey8b6xF0l7r-JNeC0k4zqM8u7z_0NWJ

/usr/local/lib/python3.8/dist-packages/gdown/cli.py:127: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1-ey8b6xF0l7r-JNeC0k4zqM8u7z_0NWJ
To: /content/house_prices.csv
100% 2.52M/2.52M [00:00<00:00, 168MB/s]


In [56]:
base = pd.read_csv('/content/house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [60]:
X = base.iloc[:, 5:6].values
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [61]:
y = base.iloc[:, 2].values
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [62]:
X.shape

(21613, 1)

In [63]:
y.shape

(21613,)

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [65]:
X_train.shape, y_train.shape

((15129, 1), (15129,))

In [66]:
X_test.shape, y_test.shape

((6484, 1), (6484,))

#LightGBM algorithm

In [67]:
LGBM = lgb.LGBMRegressor(random_state=42)

In [68]:
LGBM.fit(X_train, y_train)

LGBMRegressor(random_state=42)

In [69]:
prediction = LGBM.predict(X_test)
prediction

array([496219.12474359, 717266.7527969 , 996337.00846849, ...,
       341785.53465951, 487626.43366413, 602265.36867922])

In [70]:
y_test

array([ 365000.,  865000., 1038000., ...,  410500.,  940000.,  410000.])

##Accuracy

In [72]:
mean_squared_error(y_test, prediction)

71167345994.9362

In [77]:
grafico = px.scatter(x = y_test, y = prediction)
grafico.show()

#Saving the model with pickle

In [88]:
file = open('LGBM.pkl', 'wb')
pickle.dump(LGBM, file)
file.close()